### ISSUE TITLE
Support Firefox >51

### ISSUE THREAD

**Issue by jagajaga** [open-eid/browser-token-signing#20]
Hello! Are you going to support firefox version >51 due to https://www.bleepingcomputer.com/news/software/mozilla-to-drop-support-for-all-npapi-plugins-in-firefox-52-except-flash/?

**Comment by sainsaar** [comment]
To my knowledge chrome-token-signing works also on Firefox and replaces this one for the recent Firefoxes.

**Comment by metsma** [comment]
https://github.com/open-eid/chrome-token-signing/releases/tag/v1.0.4
