### ISSUE TITLE
browser-token-signing firefox

### ISSUE THREAD

**Issue by guesmihela** [open-eid/browser-token-signing#23]
after building browser-token-signing . I have  firefox-token-signing_3.12.0.0_x86.msi and I install it but the extension not loaded in Firefox.  there is ok  or Something to do  after installation.

**Comment by antonioaraujob** [comment]
Hi @guesmihela, as far as I know the chrome-token-signing extension works on Firefox: https://github.com/open-eid/chrome-token-signing. Firefox supports since version 50 Chrome extensions.

Regards
Antonio

**Comment by guesmihela** [comment]
@antonioaraujob I try with it but doesn't  work  in chrome and in Firefox.  but now I ask about  https://github.com/open-eid/browser-token-signing because I see that it work  for somebody else.. I work with Windows 64 . Firefox 53.0, smart  card gemalto .

**Comment by antonioaraujob** [comment]
@guesmihela You should see the pkcs11_path.c file (https://github.com/open-eid/browser-token-signing/blob/master/common/pkcs11_path.c). Maybe the ATR of your card is not recognized, therefore the driver can not be loaded.

**Comment by metsma** [comment]
https://github.com/open-eid/browser-token-signing/blob/master/README.md
There is warnig:
Warning: Firefox 52 removed NPAPI support and added Chrome Extensions support since version 50 which is implemented in chrome-token-signing

**Comment by guesmihela** [comment]
with internet explorer 11 or 10, when I run the "plugin-test.html" [here](https://github.com/open-eid/browser-token-signing/blob/master/plugin-test.html) , I have this :
Plug-in version:3.12.2 32 bit
errorMessage:Site not allowed
errorCode:19
what is the matter? 
Note: I use Gemalto as a reader card.

**Comment by metsma** [comment]
Is it https?

**Comment by guesmihela** [comment]
No. I use it from the folder browser token signing 
the url like this: file:////C:/users/user/..../plugin-test.html

**Comment by metsma** [comment]
https://github.com/open-eid/browser-token-signing/blob/ebb0ac37c3d694ff6892d27b46812b1b9ae14212/ie/EstEIDIEPluginBHO.cpp#L93
You need change the code then

**Comment by guesmihela** [comment]
I try else with wamp server : http://localhost/....

**Comment by guesmihela** [comment]
BOOL allowed = wcsstr(url_buffer, _T("https://")) == url_buffer;
change this ??? put the link like this : file:////C:/users/user/..../plugin-test.html

**Comment by guesmihela** [comment]
???

**Comment by metsma** [comment]
Plugin has to executed on https site

**Comment by guesmihela** [comment]
is there any site  https to test ?

**Comment by metsma** [comment]
https://hwcrypto.github.io/hwcrypto.js/sign.html

**Comment by guesmihela** [comment]
it works thank you  thank you ver much.god bless you
