### ISSUE TITLE
Get info certificat

### ISSUE THREAD

**Issue by ribehbl** [open-eid/browser-token-signing#24]
hello,
I have been using browser-token-signing . it worked in IE 11 but I haven't any information about the certification. Card  Reader is Gemalto. 
help plz???
![image](https://user-images.githubusercontent.com/21134826/26874313-191929e6-4b75-11e7-9785-b1c4a233294a.png)

Thanks.

**Comment by metsma** [comment]
Does certmgr.msc show your token certificates under Personal folder?

**Comment by ribehbl** [comment]
No, I have this error:
![image](https://user-images.githubusercontent.com/21134826/26876328-95545fc8-4b7d-11e7-9728-a3f2a89d79c4.png)

**Comment by metsma** [comment]
Cant understand what does it say. Maybe you have to run it as administrator "Run as" ?

**Comment by ribehbl** [comment]
I try to run it but no change, I try with  user permissions

**Comment by ribehbl** [comment]
can you give me the exact path of this file?

**Comment by metsma** [comment]
you have it on screenshot

**Comment by ribehbl** [comment]
certificat exist

**Comment by metsma** [comment]
Is this correct certificate? Does it have key usage non-repudiation bit?

**Comment by ribehbl** [comment]
yes it is correct. I can sign with it  text, but the bproblem that no info showed

**Comment by metsma** [comment]
plugin expects that cerificate has key usage non-repudiation bit

**Comment by metsma** [comment]
https://github.com/open-eid/browser-token-signing/blob/ebb0ac37c3d694ff6892d27b46812b1b9ae14212/common/cert_dialog_win.c#L48

**Comment by ribehbl** [comment]
what you means with:cerificate has key usage non-repudiation bit. how to know that???

**Comment by metsma** [comment]
Open the certificate from certmgr.msc and look the details

**Comment by ribehbl** [comment]
I havn't any information about usage non-repudiation bit.That 's means that hasn't key usage non-repudiation? what I should do so ?

**Comment by metsma** [comment]
Probably alter code (which I referenced earlier) and create custom build

**Comment by ribehbl** [comment]
it is Ok. 
thanks.

**Comment by antonioaraujob** [comment]
@ribehbl you should check if your certificate has Non-repudiation in Certificate Key Usage

![keyusage](https://user-images.githubusercontent.com/8313215/26879069-c5994f4c-4b5d-11e7-9991-b2b4a55d24a3.png)

**Comment by ribehbl** [comment]
I have this :
![Uploading image.png…]()

that means CERT_NON_REPUDIATION_KEY_USAGE.
so???

**Comment by ribehbl** [comment]
with a clic of the "showdata" link, the certificate information are undefined.
![image](https://user-images.githubusercontent.com/21134826/26880364-27565f4e-4b8c-11e7-9878-44a6f5086b16.png)

**Comment by metsma** [comment]
You have certificate DER format in HEX on the screensot.
You can parse this and extract the info?

**Comment by metsma** [comment]
Closing as I can see the certificate is received from plugin and works as expected.
