### ISSUE TITLE
Safenet token support Safari

### ISSUE THREAD

**Issue by wzoet** [open-eid/browser-token-signing#25]
Hi, I work with tokens using the safenet middleware (aka Aladdin tokens). I found it works great on FF and IE on Windows.
Unfortunately, my certificate dialog stays empty in OSX.
The safenet client is installed and the certificates are visible in it. The plugin is enabled in safari, but unfortunately no certificates are shown, a blank list pops up.
I use the latest version as available on id.ee.

**Comment by metsma** [comment]
On OS X you have to alter code to add PKCS11 driver path identified by ATR
https://github.com/open-eid/browser-token-signing/blob/master/common/pkcs11_path.c#L44

**Comment by wzoet** [comment]
Thanks for your comment. I will give it a try. 
I guess the issue is in the usage of the OpenSC library (Aladdin tokens are OpenSC compatible). In Windows the OpenSC library is used for the Estonian cards, in OSX it is a dedicated library. Of course this is no problem, but the Estonian library is being returned as default when no ATRs are found, resulting in different behavior in Windows and OSX.
I would recommend using the OpenSC library as the default in OSX as well. This will give you far more support for different kinds of tokens/cards.

**Comment by metsma** [comment]
I will reconsider OpenSC as alternative, for now I expect the  solution worked

**Comment by wzoet** [comment]
Unfortnately OpenSC didn’t do the trick. Still working on this. Also tried several drivers that came with the Safenet software, but no luck until yet.
Your solution did point me in the right direction. Please post here if you found a suitable driver, I will do the same.
