### ISSUE TITLE
how can I change language of plugin

### ISSUE THREAD

**Issue by guesmihela** [open-eid/browser-token-signing#29]
how can I change language of plugin to other language(french). 
I do this but d'ont work  in ie-token-signing.wxs : UpgradeCode="713f9d27-5016-4c6a-bee1-94403255fbd4" Id="*" Language="1036" Version="$(var.VERSION)" Codepage="1252"  
(1036 :French - France)

**Comment by metsma** [comment]
This will change only installer language. I don't think IE plugin is translated other than english
https://github.com/open-eid/browser-token-signing/blob/ebb0ac37c3d694ff6892d27b46812b1b9ae14212/ie/esteid-plugin-ie.rc

**Comment by guesmihela** [comment]
thanks for your reply . change this one  `LANGUAGE LANG_ENGLISH, SUBLANG_ENGLISH_US  `to` LANGUAGE LANG_FRENCH, SUBLANG_FRENCH_FR`????

**Comment by guesmihela** [comment]
I will try with this one  
```
#if !defined(AFX_RESOURCE_DLL) || defined(AFX_TARG_FRA)
#ifdef _WIN32
LANGUAGE LANG_FRENCH, SUBLANG_FRENCH
#pragma code_page(1252)
#endif //_WIN32
```

**Comment by guesmihela** [comment]
but d'ont work
