### ISSUE TITLE
Using a different PKCS#11 implementation in browser-token-signing.

### ISSUE THREAD

**Issue by antonioaraujob** [open-eid/browser-token-signing#3]
I have tested browser-token-signing and hwcrypto in Debian GNU/Linux 7.8 (64 bits) and it works excellent.

For Linux boxes the plugin uses `opensc-pkcs11.so` from its standard location:

```
#define LOAD_LIBRARY void *handle = dlopen("opensc-pkcs11.so", RTLD_NOW)
```

Some smart cards and USB token have a specific PKCS#11 implementation in a different file, for instance a Gemalto smart card and an Aladdin eToken PRO use the following files, respectively:

```
/usr/lib/ClassicClient/libgclib-1.8.0.so
/usr/lib64/libeTPkcs11.so
```

In these cases the plugin (through `getCertificate()` function) will not find any certificate because it is looking for `opensc-pkcs11.so` file.

Thinking in a use case in which a user does not know how to make a symbolic link from `opensc-pkcs11.so` to the hardware's PKCS#11 implementation, how could I set the path to the PKCS#11 implementation in the plugin dynamically?.

Could you please give me any advice to resolve this situation?

Best Regards

**Comment by allanjuhanson** [comment]
Hi Antonio,

This is a problem we have faced ourselves and there really doesn't seem to be a very good solution to accomplish this. One way would be to compile different versions of the plugin that use specific PKCS#11 modules. This though isn't really dynamic and the user would have to change their plugins whenever using a different token.

In our chrome token signing extension [1.0.2 beta release](https://github.com/open-eid/chrome-token-signing/releases/tag/v1.0.2-beta) we use extension options to provide the path to a specific pkcs#11 module. However in this case too the end user would have to know the correct path and the right implementation that is needed for the token that they use.

Perhaps one of the simplest solutions would be to provide shell scripts to create the required symbolic links from `opensc-pkcs11.so` to the hardware's PKCS#11 implementation but this also carries problems. 

The fourth option would be to just loop through different modules and try using them until you find one that works for the given token. This would probably mean a significant performance hit however.

So these are the options we could think of right now. Unfortunately, we have quite tight working schedule at the moment, so it is currently unsure when we would be able to offer a proper solution for this. Also bare in mind that NPAPI plugins are a dying breed and it would be probably unwise to rely on them in the long term. Chrome is removing their support for it from chrome 45 and mozilla recommends not using it for any new developments.

I hope this has been of some help and if you do implement a solution for this and think it would be of use to others as well, it would be great, if you could submit the changes that you made as a pull request.

Good luck

**Comment by antonioaraujob** [comment]
Dear Allan,
thank you very much for your detailed explanation. I really appreciate your comments.

Just one more question, if mozilla recommends not using NPAPI plugins for any new developments what will be the future of browser-token-signing for Firefox? Are you going to use only chrome-token-signing?

Best regards

**Comment by rvillido** [comment]
Hi Antonio,

We will continue supporting Firefox with browser-token-signing NPAPI plugin. We are not planning a major redesign any time soon, but in the future we would like to use a similar solution that chrome-token-signing is having. It depends what possibilities Firefox will have in the future when NPAPI is not supported anymore.

Regards

**Comment by antonioaraujob** [comment]
Dear Rainer,
Ok I understand. Thank you very much for your comments. 
chrome-token-signing looks a good solution so I am going to test it. On the other hand, I just wanted to know the browser-token-signing roadmap.

Best regards

**Comment by rvillido** [comment]
You are welcome! Let us know if you have any questions with chrome-token-signing
