### ISSUE TITLE
date valid From of certificat

### ISSUE THREAD

**Issue by guesmihela** [open-eid/browser-token-signing#31]
how can I get  date validFrom of certificat in code C++

**Comment by metsma** [comment]
Use openssl or windows/OSX crypto apis

**Comment by guesmihela** [comment]
how  in openssl ???  X509_get_notBefore(x)??
can you  give me an exemple please,
I'am really sorry  if I bother you

**Comment by metsma** [comment]
https://github.com/open-eid/libdigidocpp/blob/master/src/crypto/X509Cert.cpp#L530-L539

**Comment by guesmihela** [comment]
thank you very  much . I want to retrieve  date creation   of plugin  when  can I retrieve in  code https://github.com/open-eid/browser-token-signing
it is in esteid_time.h  No.

**Comment by guesmihela** [comment]
@metsma  I want to retrieve date creation of plugin  in code https://github.com/open-eid/browser-token-signing how  can return it
