### ISSUE TITLE
can not update id card software

### ISSUE THREAD

**Issue by bond4u** [open-eid/browser-token-signing#32]
Cannot update software because cannot uninstall previous version because .msi file is missing.

![image](https://user-images.githubusercontent.com/66413/29280964-d99953a4-8125-11e7-95b3-e61e00fc7cfb.png)

**Comment by metsma** [comment]
You can find packages here https://installer.id.ee/media/windows/installer/
And please read https://github.com/open-eid/org/blob/master/CONTRIBUTING.md#issues-and-support
