### ISSUE TITLE
installer

### ISSUE THREAD

**Issue by guesmihela** [open-eid/browser-token-signing#36]
how can I change installer language to French I add French ressources  in this one
https://github.com/open-eid/browser-token-signing/blob/ebb0ac37c3d694ff6892d27b46812b1b9ae14212/ie/esteid-plugin-ie.rc . is there any other one file to change to work  installer in French???     

// French resources

#if !defined(AFX_RESOURCE_DLL) || defined(AFX_TARG_FRA)
LANGUAGE LANG_FRENCH, SUBLANG_FRENCH
#pragma code_page(1252)

#ifdef APSTUDIO_INVOKED
/////////////////////////////////////////////////////////////////////////////
//
// TEXTINCLUDE
//

1 TEXTINCLUDE 
BEGIN
    "resource.h\0"
END

2 TEXTINCLUDE 
BEGIN
    "#ifndef APSTUDIO_INVOKED\r\n"
    "#include ""targetver.h""\r\n"
    "#endif\r\n"
    "#include ""winres.h""\r\n"
    "\0"
END

3 TEXTINCLUDE 
BEGIN
    "1 TYPELIB ""esteidpluginie.tlb""\r\n"
    "\0"
END

#endif    // APSTUDIO_INVOKED

/////////////////////////////////////////////////////////////////////////////
//
// Version
//

VS_VERSION_INFO VERSIONINFO
 FILEVERSION MAJOR_VER,MINOR_VER,RELEASE_VER,BUILD_VER
 PRODUCTVERSION MAJOR_VER,MINOR_VER,RELEASE_VER,BUILD_VER
 FILEFLAGSMASK 0x3fL
#ifdef _DEBUG
 FILEFLAGS 0x1L
#else
 FILEFLAGS 0x0L
#endif
 FILEOS 0x4L
 FILETYPE 0x2L
 FILESUBTYPE 0x0L
BEGIN
    BLOCK "StringFileInfo"
    BEGIN
        BLOCK "040904e4"
        BEGIN
            VALUE "CompanyName", ""
            VALUE "FileDescription", "tn-Sign plugin"
            VALUE "FileVersion", VER_STR(MAJOR_VER.MINOR_VER.RELEASE_VER.BUILD_VER)
            VALUE "LegalCopyright", "(c)"
            VALUE "InternalName", "tn-Sign-plugin-ie.dll"
            VALUE "OriginalFilename", "tn-Sign-plugin-ie.dll"
            VALUE "ProductName", "tn-Sign plugin"
            VALUE "ProductVersion", VER_STR(MAJOR_VER.MINOR_VER.RELEASE_VER.BUILD_VER)
        END
    END
    BLOCK "VarFileInfo"
    BEGIN
        VALUE "Translation", 0x40c, 1200
    END
END

/////////////////////////////////////////////////////////////////////////////
//
// REGISTRY
//

IDR_ESTEIDPLUGINIE      REGISTRY                "esteid-plugin-ie.rgs"
IDR_ESTEIDIEPLUGINBHO   REGISTRY                "EstEIDIEPluginBHO.rgs"
IDR_ESTEIDCERTIFICATE   REGISTRY                "EstEIDCertificate.rgs"
#endif    // French resources

**Comment by metsma** [comment]
Maybe this helps http://wixtoolset.org/documentation/manual/v3/wixui/wixui_localization.html

**Comment by metsma** [comment]
https://blogs.msdn.microsoft.com/robmen/2004/11/30/creating-localized-msi-files-using-wix-toolset-and-wxl-files/

**Comment by guesmihela** [comment]
thanks it works
