### ISSUE TITLE
Add support for custom messages in the PIN prompt when signing

### ISSUE THREAD

**Issue by Pablo-Merino** [open-eid/browser-token-signing#6]
Hello! I'm Pablo, from Stampery (https://stampery.com). We are implementing file signing using the smart cards and we are missing the ability to set a custom message into the PIN prompt so we can let the user know which file he's inputting the PIN for, since we have the ability to drag and drop multiple files.

The problem arose when we tried to sign 5 files at the time, and using the Estonian eResidency card, it worked, but kept asking the PIN 5 times.

We know it might be hard to make it so once you input the PIN it stays in memory for, let's say, a minute, as well as the security implications this might have, so we thought next that the best thing would be to give the user feedback on which file is being signed and how many are left.

Thanks and congratulations for such understandable code and nice implementations!

**Comment by martinpaljak** [comment]
It has been a long way coming. But due to FF also getting native messaging support in version 50, a revamping of the chrome plugin will happen (probably also with a rename) that will have a chance of adding new features.

**Comment by Telgat** [comment]
https://github.com/open-eid/chrome-token-signing/pull/44 should help with that
