### ISSUE TITLE
Dynamic opensc-pkcs11.so

### ISSUE THREAD

**Issue by jagajaga** [open-eid/browser-token-signing#7]
Hello. Trying to install this plugin.
But at testing page I receive: 

```
EstEID Plugin initialization failed:
dlopen failed: opensc-pkcs11.so: cannot open shared object file: No such file or directory
```

Tried to patch `Makefile` with `sed -i "s|opensc-pkcs11.so|/path/to/lib/pkcs11/opensc-pkcs11.so|" Makefile`. But that didn't help me anyway.

**Comment by jagajaga** [comment]
Cc @metsma

**Comment by metsma** [comment]
Can you verify that your opensc-pkcs11 module is usable.
`pkcs11-tool --module=/path/to/opensc-pkcs11.so -I`
I wonder that it is not full path in code and should find module ld.config path.

**Comment by jagajaga** [comment]
@metsma 

``` bash
% pkcs11-tool --module=/nix/store/z07y5p4gw3frl90b3xs80j3ysc87cf31-opensc-0.15.0/lib/pkcs11/opensc-pkcs11.so -I
Cryptoki version 2.20
Manufacturer     OpenSC (www.opensc-project.org)
Library          Smart card PKCS#11 API (ver 0.0)
Using slot 1 with a present token (0x1)
```

**Comment by metsma** [comment]
I this build path or system layout?

**Comment by jagajaga** [comment]
Even if I run with no `--module` I get

``` bash
pkcs11-tool -I
Cryptoki version 2.20
Manufacturer     OpenSC (www.opensc-project.org)
Library          Smart card PKCS#11 API (ver 0.0)
Using slot 1 with a present token (0x1)
```

**Comment by jagajaga** [comment]
@metsma system layout.

**Comment by metsma** [comment]
does this system have ld.config?

**Comment by metsma** [comment]
You probably need to add lib/pkcs11 to ld config path

**Comment by jagajaga** [comment]
I need to provide it to a build time?

**Comment by metsma** [comment]
Linux has configuration files where to find shared libraries
`cat /etc/ld.so.conf.d/libc.conf    
/usr/local/lib`

**Comment by jagajaga** [comment]
Ok, I've fixed `EstEID Plugin initialization failed: dlopen failed: opensc-pkcs11.so: cannot open shared object file: No such file or directory` error. Now I don't have it.

But now on a test page I'm getting

```
id:     
CN:     
issuerCN:   
validFrom:  
validTo:    
errorMessage: Site is not allowed
errorCode: 19
PEM:

DER in hex:
```

And at https://sisene.www.eesti.ee/idportaal/login.html I'm still getting `SSL_ERROR_HANDSHAKE_FAILURE_ALERT`

**Comment by jagajaga** [comment]
With `make plugin-development` (is it ok?) test page worked! I signed something and everything is ok. Yay!
But https://sisene.www.eesti.ee/idportaal/login.html is still giving me `SSL_ERROR_HANDSHAKE_FAILURE_ALERT`. Maybe I need to install some additional things, @metsma?

**Comment by metsma** [comment]
Site should be over ssl you can test plugin on this page
https://open-eid.github.io/hwcrypto.js/sign.html

Plugin has nothing to do with https auth or login
For this you need load pkcs11 plugin to Firefox
Settings->Advanced->Certificates->Security devices->Load
and add onepin-opensc-pkcs11.so

This is helper extension but it does not work for you, different pkcs11 paths.
https://github.com/open-eid/firefox-pkcs11-loader

**Comment by jagajaga** [comment]
Thank you! Now everythings work.
